### ISSUE TITLE
Unable to set framerate with using the FPSManager

### ISSUE THREAD

**Issue by julianofoleiss** [py-sdl/py-sdl2#239]
**What doesn't work?**
I'm trying to use the `FPSManager` from the `sdl2.sdlgfx` module to make my application run at 60FPS. However, I keep getting 30FPS.

**How To Reproduce**
```python
import sys
import sdl2
import sdl2.ext
import sdl2.sdlgfx

def run():
    sdl2.ext.init()
    window = sdl2.ext.Window("TEST", size=(800,600))
    window.show()

    fpsManager = sdl2.sdlgfx.FPSManager(rate=60)
    sdl2.sdlgfx.SDL_setFramerate(fpsManager, 60)

    running = True
    while running:
        events = sdl2.ext.get_events()
        for event in events:
            if event.type == sdl2.SDL_QUIT:
                running = False
                break

        window.title = "%s - %d FPS" % ("TEST", sdl2.sdlgfx.SDL_getFramerate(fpsManager))
        sdl2.sdlgfx.SDL_framerateDelay(fpsManager)

    sdl2.ext.quit()

    return 0

if __name__ == "__main__":
    sys.exit(run())

```

**Platform (if relevant):**
 - OS: Ubuntu Linux 20.04
 - Python Version: Python 3.8.10
 - SDL2 Version: 2.0.22.post1 
 - PySDL2 Version: 0.9.12
 - Using pysdl2-dll: Yes (I tried without pysdl2-dll and I still get the same results)

**Comment by a-hurst** [comment]
Hi @julianofoleiss, thanks for the detailed and reproducible report! I just tested this on my end and found the issue: the `FPSManager` from gfx needs to be initialized first with `sdl2.sdlgfx.SDL_initFramerate` before it can actually be used. Adding `sdl2.sdlgfx.SDL_initFramerate(fpsManager)` on the line after you create `fpsManager` fixes the example on my end.

I'll make a note in the gfx docs for `FPSManager` mentioning it needs to be initialized to clear up future confusion. Thanks again!

**Comment by julianofoleiss** [comment]
Hello @a-hurst! Thanks for the response! I just verified that calling `sdl2.sdlgfx.SDL_initFramerate` right after instantiating `FPSManager` fixes the Issue!

Thank you very much!
