### ISSUE TITLE
test_Mix_MusicDuration failure: assert 0.2 < 0.1501...

### ISSUE THREAD

**Issue by smcv** [py-sdl/py-sdl2#243]
**What doesn't work?**
While trying to update the `pysdl2` package in Debian from 0.9.9 to 0.9.13, I got a test failure:

```
    @pytest.mark.skipif(sdlmixer.dll.version < 2060, reason="Added in 2.6.0")
    def test_Mix_MusicDuration(with_music):
        mus = with_music
        duration = sdlmixer.Mix_MusicDuration(mus)
        assert duration != 0
>       assert 0.2 < duration < 0.21
E       assert 0.2 < 0.15015873015873016
```

**How To Reproduce**
Run the test suite

**Platform (if relevant):**
 - OS: Debian `unstable` rolling release/development distribution
 - Python Version: 3.10.6
 - SDL2 Version: 2.0.22
 - Using pysdl2-dll: No

**Additional context**

Debian's SDL2_mixer is version 2.6.1, compiled to use libmpg123 for MP3 audio.

I tried loading `sdl2/test/resources/soundtest.mp3` with `extract(1)` and Audacity, both of which agree its length is approximately 0.15 seconds, rather than the 0.2 that the test wants.

Is there some other MP3 decoder that thinks this file is 0.2s long?

**Comment by a-hurst** [comment]
@smcv This looks like a bug in `SDL_mixer`'s new default drmp3 backend, which is what their current pre-compiled binaries use and what I was using when I wrote the test. I'll merge your fix to address the immediate problem, but this is also something that the Mixer team should be aware of.

Thanks for double-checking with other audio tools to confirm it's not an mpg123 bug!
