### ISSUE TITLE
How to convert SDL_Surface to pygame.Surface?

### ISSUE THREAD

**Issue by MestreLion** [py-sdl/py-sdl2#250]
This is actually a question, not a feature request, but I'm willing to create a PR for docs and/or new method if anyone finds this useful:

Currently I'm planning to use `py-sdl2` for the sole purpose of loading SVG files into Pygame, as `pygame.image.load()` now does accept SVG files but it lacks `width`, `height` arguments to choose the rendering size, so it renders only to nominal size  (similar to `sdl2.sdlimage.IMG_LoadSVG_RW`), which is kind of useless.

That said, I believe `sdl2.ext.image.load_svg()` is the proper tool for the job. But... how can I convert the object returned to a `pygame.Surface`? I guess the two are very similar, so how to go from one to the other?

I believe it would be something like:
```python
def render_vector(path: str, width: int, height: int) -> pygame.Surface:
    sdlsurf = sdl2.ext.load_svg(file, width, height)
    buf = ...  # how to get a buffer of pixels from sdlsurf?
    format = ...  # "RGBA"?
    pysurf = pygame.image.frombuffer(buf, (width, height), format)
    ...  # should I free any structure? any cleanup code required?
    return pysurf.convert_alpha()  # is convert_alpha() really necessary in this case?
```

Any help is greatly appreciated.

If needed, I can send a PR to add this "recipe" to one of pysdl2's tutorials or create an ext wrapper for it.

**Comment by a-hurst** [comment]
Hi @MestreLion, do you know if Pygame can read in images from Numpy arrays? If so, you should be able to use `sdl2.ext.surface_to_ndarray` to convert it to a Numpy array, then load that into a Pygame surface (either directly or by casting the array to bytes).

No clue if it's possible without the additional Numpy dependency, but the source for `sdl2.ext.surface_to_ndarray` might give you some ideas!

**Comment by a-hurst** [comment]
@MestreLion Ah yep, `SDL_image` uses nanoSVG as a backend, which is small/simple/portable but is definitely a bit limited when it comes to full-fat SVG libraries. My own testing found that older and simpler SVGs were generally okay, but newer and more complex ones could break dramatically.

Glad you found something that works, though I hope something better for Python SVG rendering comes along!
