### ISSUE TITLE
How to delete UserWarning: Using SDL2 binaries from pysdl2-dll 2.28.0

### ISSUE THREAD

**Issue by dimkauzh** [py-sdl/py-sdl2#264]
Hi, so I'm using pysdl2 and pysdl2-dll on mac and everytime I run my code I get this userwarning:
```bash
UserWarning: Using SDL2 binaries from pysdl2-dll 2.28.0
```

**Comment by a-hurst** [comment]
If you want to hide the warning, all you need to do is suppress warnings when you import PySDL2:

```python
import warnings
with warnings.catch_warnings():	
	warnings.simplefilter("ignore")
	import sdl2
```

**Comment by dimkauzh** [comment]
@a-hurst will it delete all pysdl2 warnings? or only this one?

**Comment by dimkauzh** [comment]
> @dimkauzh Only the one that occurs during import! Anything outside of the `with warnings.catch_warnings()` context will raise errors/warnings like normal.

But if I get any weird error during import, will it be shown?

**Comment by a-hurst** [comment]
@dimkauzh If you hit any actual errors/exceptions during import, those will still get raised as usual. The code above only suppresses *warnings* (i.e. non-fatal errors). If there's an actual problem of some kind importing pysdl2, it'll still throw an exception.

**Comment by dimkauzh** [comment]
> throw

Okay thanks!
